[package]
name = "console"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
logger = { path = "../logger" }

[dependencies.sdl2]
version = "0.35.1"
features = ["ttf"]
