[package]
name = "tile_convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tilemap = { path = "../tilemap" }
clap = "3.2.17"