[package]
name = "threaded_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
rand = "0.8.5"
png = "0.17.5"
rayon = "1"