[package]
name = "julia"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"cmd-switch" = { path = "../cmd-switch" }
"image" = "0.23.14"
"num" = "0.4.0"







