[package]
name = "code2text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_lex = { path = "../rs_lex" }
logger = { path = "../logger" }
clap = "3.2.21"
rand = "0.8.5"
rayon = "1"
